name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_SSH_PORT || 22 }}
          script_stop: true
          script: |
            cd /home/ubuntu/react-nest/server
            sudo rm -f .env
            echo "${{ secrets.ENV }}" | sudo tee .env
            sudo git pull origin main
            sudo yarn
            sudo yarn build
            sudo pm2 kill
            sudo pm2 start dist/main.js --name "pullim-server"
